service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-southeast-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: index-photos-2
    handler: lambda.handler
    description: test-lambda
    timeout: 15 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"